apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tomcat-service
    spec:
      initContainers:
      - name: agent-repo
        image: appddave/agent-repo:4.4
        imagePullPolicy: Always
        command: ["cp", "/sharedFiles/AppServerAgent.zip", "/mountPath/AppServerAgent.zip"]
        command: ["cp", "/sharedFiles/startup.sh", "/mountPath/startup.sh"]
        command: ["cp", "/sharedFiles/extractAgent.sh", "/mountPath/extractAgent.sh"]
        volumeMounts:
        - mountPath: /mountPath
          name: shared-files
      volumes:
        - name: shared-files
          emptyDir: {}
      serviceAccountName: appd-agent
      containers:
        - name: tomcat-service
          image: tomcat:9
          imagePullPolicy: Always
          command: ["/sharedFiles/startup.sh"]
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: controller-config
          env:
            - name: TIER_NAME
              value: JavaApp
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /sharedFiles
              name: shared-files
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: appddave-tomcat-service
spec:
  selector:
    name: tomcat-service
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}
